### PR TITLE
Add spinner-*

### PR DESCRIPTION
**Pull request by aniketd**

### CODE REVIEW

**Comment by mschristiansen** [comment]
Thanks! Would you like me to make a new release or do you think you have a few more changes coming?

**Comment by aniketd** [comment]
Hey! Thanks for merging... I am compelled to complete all the missing class names, but haven't found the time to do that yet. If you don't get an update from me within the week (I'm planning to take some time to do that), go ahead please.

**Comment by mschristiansen** [comment]
Sounds good. Don't be shy to send me a nudge if there is anything you need
from me.

Mikkel S. Christiansen
Cell +27 82 727 4670

**Comment by aniketd** [comment]
@mschristiansen :1st_place_medal: Thanks a ton! :+1: :heart:

**Pull request merged**
